version: '3.9'

services:
  database:
    image: postgres:13.4-alpine
    container_name: tt_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: ndrew
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432