version: '3.9'

services:
  database-test:
    image: postgres:13.4-alpine
    container_name: tt_db_test
    environment:
      POSTGRES_DB: db_name_test
      POSTGRES_USER: ndrew
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432