version: '3.9'

services:
  tt-go-api:
    container_name: tt-go-sample-api
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    command: [ "/app/main" ]
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tt-network

  database:
    image: postgres:13.4-alpine
    container_name: tt_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: ndrew
      POSTGRES_PASSWORD: db_pass
    ports:
      - "5432:5432"
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -d db_name -U ndrew"]
      interval: 3s
      timeout: 60s
      retries: 5
      start_period: 10s
    networks:
      - tt-network

networks:
  tt-network:
    name: tt-network
    driver: bridge